### PR TITLE
Rework help system (again) to reduce channel noise.

### PR DESCRIPTION
**Pull request by rwjblue**
Attempts to follow the discussion in #14. 

.help would output:

```
00:01 < rwjblue> .help
00:01 < turbot_> Hi, I'm turbot. I know how to respond to many commands (I also accept pull requests for more). For more information on any of them execute .help <command name>.
00:01 < turbot_> '.chuck norris', '.chuck says', '.chuck', .cowsay, .rule of acquisition, .gem <search term>, .gem info <search term>, '.github status', '.github last message', 
                 '.make me a sandwich', .nextmeetup, '.joke me', '.joke', .turbotinfo, .ddg, .help
```

.help <some matcher text> would output:

```
09:02 < rwjblue> .help github
09:02 < turbot_> +------------------------+-----------------------------------------------------------------------------------------------------+
09:02 < turbot_> | Matchers               | Description                                                                                         |
09:02 < turbot_> +------------------------+-----------------------------------------------------------------------------------------------------+
09:02 < turbot_> | '.github status'       | Show latest status update for Github. (will auto-print every 5 minutes when github is having issues |
09:02 < turbot_> | '.github last message' | Show latest manual status update for Github.                                                        |
09:02 < turbot_> +------------------------+-----------------------------------------------------------------------------------------------------+
```

### CODE REVIEW

**Comment by pwelch** [comment]
Looks like the build failed. Could you take a look at it [here](https://travis-ci.org/rondale-sc/turbot/builds/4180146) to see if it is an issue?

**Comment by rwjblue** [comment]
Crap, good job Travis! 

I had changed some of the text in the reply. I'll get it fixed up ASAP.

**Comment by rwjblue** [comment]
OK, just fixed the test.  The Build is good to go...

**Comment by rwjblue** [comment]
Updated .help <some matcher> to print ASCII table.

**Comment by rondale-sc** [comment]
closes #14

**Pull request merged**
